### ISSUE TITLE
Please release version 10.1.x

### ISSUE THREAD

**Issue by philippn** [webjars/highlightjs#19]
Hi there,

It's been awhile since the last update and version 10 is out now. Could you please update it? 

Thanks in advance for your efforts and keep up the good work!

Kind regards,
Philipp

**Comment by jamesward** [comment]
Can you use the NPM WebJar instead?  Maintaining the manual / classic one is a bit tedious.  I've deployed the latest:
```
GroupID = org.webjars.npm
ArtifactID = highlight.js
Version = 10.1.2
```

**Comment by philippn** [comment]
Hi there,
unfortunately I cannot use the NPM version :-(
