### ISSUE TITLE
Please Release new version

### ISSUE THREAD

**Issue by Fynn96** [webjars/highlightjs#21]
Hey there!

I am trying to use HighlightJS with Maven and found your release. Unfortunately there are some bug fixes in the newer versions that I really need. Would it be possible for you to release a new version? 

Thank you!

**Comment by bsanchezb** [comment]
I support @Fynn96 in this request and also would like to see a new version of HighlightJS released on Maven.

Thank you!

**Comment by jamesward** [comment]
Of course! Version `11.5.0` will be released shortly.

**Comment by bsanchezb** [comment]
Thank you @jamesward ! Looking forward to the release.
